# Melliza - Autonomous agent loop for PRDs with Gemini CLI
# Homebrew formula for installing melliza on macOS and Linux
#
# Installation Options:
#
# Option 1: Use the tap (recommended after first release)
#   brew tap lvcoi/melliza
#   brew install melliza
#
# Option 2: Install directly from this repo
#   brew install lvcoi/melliza/melliza
#
# Option 3: Build from source
#   brew install --build-from-source lvcoi/melliza/melliza
#
# Note: This file is auto-generated by goreleaser during releases.
# The SHA256 checksums below are placeholders until the first release.

class Melliza < Formula
  desc "Autonomous agent loop for working through PRDs with Gemini CLI"
  homepage "https://github.com/lvcoi/melliza"
  version "0.1.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/lvcoi/melliza/releases/download/v#{version}/melliza_#{version}_darwin_amd64.tar.gz"
      # SHA256 will be auto-populated by goreleaser on release
      sha256 "PLACEHOLDER_DARWIN_AMD64_SHA256"

      def install
        bin.install "melliza"
      end
    end

    on_arm do
      url "https://github.com/lvcoi/melliza/releases/download/v#{version}/melliza_#{version}_darwin_arm64.tar.gz"
      # SHA256 will be auto-populated by goreleaser on release
      sha256 "PLACEHOLDER_DARWIN_ARM64_SHA256"

      def install
        bin.install "melliza"
      end
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/lvcoi/melliza/releases/download/v#{version}/melliza_#{version}_linux_amd64.tar.gz"
      # SHA256 will be auto-populated by goreleaser on release
      sha256 "PLACEHOLDER_LINUX_AMD64_SHA256"

      def install
        bin.install "melliza"
      end
    end

    on_arm do
      url "https://github.com/lvcoi/melliza/releases/download/v#{version}/melliza_#{version}_linux_arm64.tar.gz"
      # SHA256 will be auto-populated by goreleaser on release
      sha256 "PLACEHOLDER_LINUX_ARM64_SHA256"

      def install
        bin.install "melliza"
      end
    end
  end

  test do
    # Verify the binary runs and reports its version
    assert_match version.to_s, shell_output("#{bin}/melliza --version")
  end
end
